// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ko'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 안​녕
	 */
	HI: string
}

export type TranslationFunctions = {
	/**
	 * 안녕
	 */
	HI: () => LocalizedString
}

export type Formatters = {}
